const actionAWords = [
  {
    word: 'cry',
    translation: 'плакать',
    image: './img/actionA/cry.jpg',
    trainClicks: 0,
    correct: 0,
    mistake: 0,
  },
  {
    word: 'dance',
    translation: 'танцевать',
    image: './img/actionA/dance.jpg',
    trainClicks: 0,
    correct: 0,
    mistake: 0,
  },
  {
    word: 'dive',
    translation: 'нырять',
    image: './img/actionA/dive.jpg',
    trainClicks: 0,
    correct: 0,
    mistake: 0,
  },
  {
    word: 'draw',
    translation: 'рисовать',
    image: './img/actionA/draw.jpg',
    trainClicks: 0,
    correct: 0,
    mistake: 0,
  },
  {
    word: 'fish',
    translation: 'рыбачить',
    image: './img/actionA/fish.jpg',
    trainClicks: 0,
    correct: 0,
    mistake: 0,
  },
  {
    word: 'fly',
    translation: 'летать',
    image: './img/actionA/fly.jpg',
    trainClicks: 0,
    correct: 0,
    mistake: 0,
  },
  {
    word: 'hug',
    translation: 'обнимать',
    image: './img/actionA/hug.jpg',
    trainClicks: 0,
    correct: 0,
    mistake: 0,
  },
  {
    word: 'jump',
    translation: 'прыгать',
    image: './img/actionA/jump.jpg',
    trainClicks: 0,
    correct: 0,
    mistake: 0,
  },
];

const actionBWords = [
  {
    word: 'open',
    translation: 'открывать',
    image: './img/actionB/open.jpg',
    trainClicks: 0,
    correct: 0,
    mistake: 0,
  },
  {
    word: 'play',
    translation: 'играть',
    image: './img/actionB/play.jpg',
    trainClicks: 0,
    correct: 0,
    mistake: 0,
  },
  {
    word: 'point',
    translation: 'указывать',
    image: './img/actionB/point.jpg',
    trainClicks: 0,
    correct: 0,
    mistake: 0,
  },
  {
    word: 'ride',
    translation: 'ездить',
    image: './img/actionB/ride.jpg',
    trainClicks: 0,
    correct: 0,
    mistake: 0,
  },
  {
    word: 'run',
    translation: 'бегать',
    image: './img/actionB/run.jpg',
    trainClicks: 0,
    correct: 0,
    mistake: 0,
  },
  {
    word: 'sing',
    translation: 'петь',
    image: './img/actionB/sing.jpg',
    trainClicks: 0,
    correct: 0,
    mistake: 0,
  },
  {
    word: 'skip',
    translation: 'прыгать',
    image: './img/actionB/skip.jpg',
    trainClicks: 0,
    correct: 0,
    mistake: 0,
  },
  {
    word: 'swim',
    translation: 'плавать',
    image: './img/actionB/swim.jpg',
    trainClicks: 0,
    correct: 0,
    mistake: 0,
  },
];

const actionCWords = [
  {
    word: 'argue',
    translation: 'спорить',
    image: './img/actionC/argue.jpg',
    trainClicks: 0,
    correct: 0,
    mistake: 0,
  },
  {
    word: 'build',
    translation: 'строить',
    image: './img/actionC/build.jpg',
    trainClicks: 0,
    correct: 0,
    mistake: 0,
  },
  {
    word: 'carry',
    translation: 'нести',
    image: './img/actionC/carry.jpg',
    trainClicks: 0,
    correct: 0,
    mistake: 0,
  },
  {
    word: 'catch',
    translation: 'ловить',
    image: './img/actionC/catch.jpg',
    trainClicks: 0,
    correct: 0,
    mistake: 0,
  },
  {
    word: 'drive',
    translation: 'водить',
    image: './img/actionC/drive.jpg',
    trainClicks: 0,
    correct: 0,
    mistake: 0,
  },
  {
    word: 'drop',
    translation: 'падать',
    image: './img/actionC/drop.jpg',
    trainClicks: 0,
    correct: 0,
    mistake: 0,
  },
  {
    word: 'pull',
    translation: 'тянуть',
    image: './img/actionC/pull.jpg',
    trainClicks: 0,
    correct: 0,
    mistake: 0,
  },
  {
    word: 'push',
    translation: 'толкать',
    image: './img/actionC/push.jpg',
    trainClicks: 0,
    correct: 0,
    mistake: 0,
  },
];

const adjectiveWords = [
  {
    word: 'big',
    translation: 'большой',
    image: './img/adjective/big.jpg',
    trainClicks: 0,
    correct: 0,
    mistake: 0,
  },
  {
    word: 'small',
    translation: 'маленький',
    image: './img/adjective/small.jpg',
    trainClicks: 0,
    correct: 0,
    mistake: 0,
  },
  {
    word: 'fast',
    translation: 'быстрый',
    image: './img/adjective/fast.jpg',
    trainClicks: 0,
    correct: 0,
    mistake: 0,
  },
  {
    word: 'slow',
    translation: 'медленный',
    image: './img/adjective/slow.jpg',
    trainClicks: 0,
    correct: 0,
    mistake: 0,
  },
  {
    word: 'friendly',
    translation: 'дружелюбный',
    image: './img/adjective/friendly.jpg',
    trainClicks: 0,
    correct: 0,
    mistake: 0,
  },
  {
    word: 'unfriendly',
    translation: 'недружелюбный',
    image: './img/adjective/unfriendly.jpg',
    trainClicks: 0,
    correct: 0,
    mistake: 0,
  },
  {
    word: 'young',
    translation: 'молодой',
    image: './img/adjective/young.jpg',
    trainClicks: 0,
    correct: 0,
    mistake: 0,
  },
  {
    word: 'old',
    translation: 'старый',
    image: './img/adjective/old.jpg',
    trainClicks: 0,
    correct: 0,
    mistake: 0,
  },
];

const animalAWords = [
  {
    word: 'cat',
    translation: 'кошка',
    image: './img/animalA/cat.jpg',
    trainClicks: 0,
    correct: 0,
    mistake: 0,
  },
  {
    word: 'chick',
    translation: 'цыплёнок',
    image: './img/animalA/chick.jpg',
    trainClicks: 0,
    correct: 0,
    mistake: 0,
  },
  {
    word: 'chicken',
    translation: 'курица',
    image: './img/animalA/chicken.jpg',
    trainClicks: 0,
    correct: 0,
    mistake: 0,
  },
  {
    word: 'dog',
    translation: 'собака',
    image: './img/animalA/dog.jpg',
    trainClicks: 0,
    correct: 0,
    mistake: 0,
  },
  {
    word: 'horse',
    translation: 'лошадь',
    image: './img/animalA/horse.jpg',
    trainClicks: 0,
    correct: 0,
    mistake: 0,
  },
  {
    word: 'pig',
    translation: 'свинья',
    image: './img/animalA/pig.jpg',
    trainClicks: 0,
    correct: 0,
    mistake: 0,
  },
  {
    word: 'rabbit',
    translation: 'кролик',
    image: './img/animalA/rabbit.jpg',
    trainClicks: 0,
    correct: 0,
    mistake: 0,
  },
  {
    word: 'sheep',
    translation: 'овца',
    image: './img/animalA/sheep.jpg',
    trainClicks: 0,
    correct: 0,
    mistake: 0,
  },
];

const animalBWords = [
  {
    word: 'bird',
    translation: 'птица',
    image: './img/animalB/bird.jpg',
    trainClicks: 0,
    correct: 0,
    mistake: 0,
  },
  {
    word: 'fish',
    translation: 'рыба',
    image: './img/animalB/fish.jpg',
    trainClicks: 0,
    correct: 0,
    mistake: 0,
  },
  {
    word: 'frog',
    translation: 'лягушка',
    image: './img/animalB/frog.jpg',
    trainClicks: 0,
    correct: 0,
    mistake: 0,
  },
  {
    word: 'giraffe',
    translation: 'жираф',
    image: './img/animalB/giraffe.jpg',
    trainClicks: 0,
    correct: 0,
    mistake: 0,
  },
  {
    word: 'lion',
    translation: 'лев',
    image: './img/animalB/lion.jpg',
    trainClicks: 0,
    correct: 0,
    mistake: 0,
  },
  {
    word: 'mouse',
    translation: 'мышь',
    image: './img/animalB/mouse.jpg',
    trainClicks: 0,
    correct: 0,
    mistake: 0,
  },
  {
    word: 'turtle',
    translation: 'черепаха',
    image: './img/animalB/turtle.jpg',
    trainClicks: 0,
    correct: 0,
    mistake: 0,
  },
  {
    word: 'dolphin',
    translation: 'дельфин',
    image: './img/animalB/dolphin.jpg',
    trainClicks: 0,
    correct: 0,
    mistake: 0,
  },
];

const clothesWords = [
  {
    word: 'skirt',
    translation: 'юбка',
    image: './img/clothes/skirt.jpg',
    trainClicks: 0,
    correct: 0,
    mistake: 0,
  },
  {
    word: 'pants',
    translation: 'штаны',
    image: './img/clothes/pants.jpg',
    trainClicks: 0,
    correct: 0,
    mistake: 0,
  },
  {
    word: 'blouse',
    translation: 'блузка',
    image: './img/clothes/blouse.jpg',
    trainClicks: 0,
    correct: 0,
    mistake: 0,
  },
  {
    word: 'dress',
    translation: 'платье',
    image: './img/clothes/dress.jpg',
    trainClicks: 0,
    correct: 0,
    mistake: 0,
  },
  {
    word: 'boot',
    translation: 'ботинки',
    image: './img/clothes/boot.jpg',
    trainClicks: 0,
    correct: 0,
    mistake: 0,
  },
  {
    word: 'shirt',
    translation: 'рубашка',
    image: './img/clothes/shirt.jpg',
    trainClicks: 0,
    correct: 0,
    mistake: 0,
  },
  {
    word: 'coat',
    translation: 'платье',
    image: './img/clothes/coat.jpg',
    trainClicks: 0,
    correct: 0,
    mistake: 0,
  },
  {
    word: 'shoe',
    translation: 'туфли',
    image: './img/clothes/shoe.jpg',
    trainClicks: 0,
    correct: 0,
    mistake: 0,
  },
];

const emotionWords = [
  {
    word: 'sad',
    translation: 'грустный',
    image: './img/emotion/sad.jpg',
    trainClicks: 0,
    correct: 0,
    mistake: 0,
  },
  {
    word: 'angry',
    translation: 'сердитый',
    image: './img/emotion/angry.jpg',
    trainClicks: 0,
    correct: 0,
    mistake: 0,
  },
  {
    word: 'happy',
    translation: 'счастливый',
    image: './img/emotion/happy.jpg',
    trainClicks: 0,
    correct: 0,
    mistake: 0,
  },
  {
    word: 'tired',
    translation: 'уставший',
    image: './img/emotion/tired.jpg',
    trainClicks: 0,
    correct: 0,
    mistake: 0,
  },
  {
    word: 'surprised',
    translation: 'удивленный',
    image: './img/emotion/surprised.jpg',
    trainClicks: 0,
    correct: 0,
    mistake: 0,
  },
  {
    word: 'scared',
    translation: 'испуганный',
    image: './img/emotion/scared.jpg',
    trainClicks: 0,
    correct: 0,
    mistake: 0,
  },
  {
    word: 'smile',
    translation: 'улыбка',
    image: './img/emotion/smile.jpg',
    trainClicks: 0,
    correct: 0,
    mistake: 0,
  },
  {
    word: 'laugh',
    translation: 'смех',
    image: './img/emotion/laugh.jpg',
    trainClicks: 0,
    correct: 0,
    mistake: 0,
  },
];

export {
  actionAWords,
  actionBWords,
  actionCWords,
  adjectiveWords,
  animalAWords,
  animalBWords,
  clothesWords,
  emotionWords,
};
